Repository EntryDSM/Yapaghetti, pull requests merged in 2022-08, with the labels that each got.

#174 🔀 :: (#173) 이미지 업로드 에러 수정
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/image/presentation/ImageWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/infrastructure/s3/AwsS3Adapter.java
Labels: 버그, chore

#177 🔀 :: (#176) WebConfig 설정
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/config/WebConfig.java
Labels: 프로젝트 설정, 기능 추가

#179 🔀 :: (#178) 이미지 업로드 이후 임시파일 삭제 & method 명 수정
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/image/presentation/ImageWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/infrastructure/s3/AwsS3Adapter.java
Labels: chore

#182 🔀 :: (#181) ErrorFilter에서 InternalServerError 일 때 StackTrace를 출력
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/error/filter/GlobalErrorFilter.java
Labels: 기능 추가, chore

#184 🔀 :: (#183) Redis password 설정
  yapaghetti-infrastructure/src/main/resources/application.yml
Labels: 버그, chore

#186 🔀 :: (#185) 서비스 Layer에 Transaction 적용
  .gitignore
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/annotation/ReadOnlyUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/usecase/QueryStudentListUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryLocalDocumentListUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryLocalDocumentUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryProtectedDocumentUrlUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryPublicDocumentUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryStayAndPublicDocumentPreviewUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryStayDocumentUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/usecase/QueryMyInfoUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/QueryTagListUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/GetCompanyDetailUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/QueryCompanyListUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/QueryStudentDetailUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/TeacherQueryStudentListUseCase.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/annotation/config/GlobalComponentScan.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/aop/TransactionAspect.java
  yapaghetti-infrastructure/src/main/resources/application.yml
Labels: chore

#190 🔀 : (#189) Type 변경
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/CompanyElement.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/QueryCompanyListTest.java
Labels: 버그, 리팩토링

#188 🔀 :: (#187) 최초 비밀번호 수정 Api 체크
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/error/UserErrorCode.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/exception/AlreadyVisitException.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/FirstPasswordUpdateUseCase.java
Labels: 버그

#197 🔀 :: (#196) @Max는 숫자 타입에, String valid check는 @Size로!
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/presentation/dto/request/WebAddTagRequest.java
Labels: 버그, chore

#200 🔀 :: (#180) 학생 리스트 오류
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/StudentElementByGradeClassNum.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
Labels: 버그

#202 🔀 :: (#201) 학생 상세보기 오류
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/StudentDetailResponse.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
Labels: 버그

#199 🔀 :: (#198) Teacher 부분 코드 정리
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/request/DomainNewCompanyRequest.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/request/DomainUpdateCompanyRequest.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/CompanyDetailResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherCommandUserPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/CreateCompanyUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/GetCompanyDetailUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/UpdateCompanyUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/domain/User.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/UpdateCompanyTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/TeacherWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/dto/request/WebCreateCompanyRequest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/dto/request/WebCreateFeedbackRequest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/dto/request/WebUpdateCompanyRequest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserPersistenceAdapter.java
Labels: 리팩토링

#205 🔀 :: (#204) 학생 삭제 오류
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/mapper/StudentMapper.java
Labels: 버그
