Repository EntryDSM/Yapaghetti, pull requests merged in 2022-09, with the labels that each got.

#209 🔀 :: (#203) 기업 삭제 오류 해결
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/mapper/CompanyMapper.java
Labels: 리팩토링

#208 🔀 :: (#207) 학생 상세 보기 이미지 url 추가
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/StudentDetailResponse.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/QueryStudentDetailTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
Labels: 리팩토링

#211 🔀 :: (#180) 학생 전체 리스트 수정
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/TeacherWebAdapter.java
Labels: 리팩토링

#212 🔀 :: (#180) 문서 없는 학생도 리스트에 나오게 변경
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
Labels: chore

#213 🔀 :: (#206) 기업 생성 에러 해결
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/CreateCompanyUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/CreateCompanyUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/mapper/CompanyMapper.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/CompanyPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/entity/CompanyEntity.java
Labels: 버그, 리팩토링

#214 🔀 :: (#180) 학생 리스트 중복 제거
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
Labels: chore

#218 🔀 :: (#217) myskill 엔티티 unique 속성 추가
  .gitignore
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/entity/MySkillEntity.java
Labels: chore

#216 🔀 :: (#215) version 수정
  .github/workflows/CD.yml
Labels: chore

#226 🔀 :: (#225) Local Document 조회 에러 수정
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryLocalDocumentUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryLocalDocumentUseCaseTest.java
Labels: 버그, 리팩토링

#224 🔀 :: (#223) @Size 설정
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/dto/request/WebCreateLocalDocumentRequest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/dto/request/WebUpdateLocalDocumentRequest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/dto/request/WebUpdateStayDocumentRequest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/presentation/dto/request/WebFirstPasswordUpdateRequest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/presentation/dto/request/WebSignInRequest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/presentation/dto/request/WebUpdateUserInformationRequest.java
Labels: chore

#221 🔀 :: (#220) isMou 추가
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/CompanyDetailResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/GetCompanyDetailUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/GetCompanyDetailUseCaseTest.java
Labels: chore

#227 🔀 :: (#210) 피드백 추가 오류
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/CreateFeedbackUseCase.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/entity/DocumentEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/mapper/FeedbackMapper.java
Labels: 버그

#229 🔀 :: (#228) infrastructure -> thirdparty로 패키지명 변경
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/thirdparty/s3/AwsS3Adapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/thirdparty/ses/AwsSESAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/thirdparty/ses/AwsSESConfig.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/thirdparty/sms/CoolSmsAdapter.java
Labels: 프로젝트 설정, 리팩토링, chore

#231 🔀 :: (#230) 공개 요청 취소 Api 버그 해결
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/mapper/DocumentMapper.java
Labels: 버그, 리팩토링, chore

#233 🔀 :: (#232) 기업 정보 수정 Api 변경
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/api/dto/request/DomainUpdateCompanyNameRequest.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/spi/CompanyCommandUserPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/spi/CompanyQueryUserPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/usecase/UpdateCompanyNameUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/UserPort.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/company/usecase/UpdateCompanyNameUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/presentation/CompanyWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/presentation/dto/request/WebUpdateCompanyInformationRequest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/presentation/dto/request/WebUpdateCompanyNameRequest.java
Labels: 기능 추가

#236 🔀 :: (#175) 패키지 구조 통일
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/annotation/config/AnnotationConfig.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/filter/FilterConfig.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/web/WebConfig.java
Labels: 리팩토링

#242 🔀 :: (#240) 문서 Id 넘겨주기
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/api/dto/response/StudentElement.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
Labels: chore

#241 🔀 :: (#239) 기업 정보 조회 Api 구현
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/api/QueryCompanyInfoPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/api/dto/response/QueryCompanyInfoResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/usecase/QueryCompanyInfoUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/company/usecase/QueryCompanyInfoUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/presentation/CompanyWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
Labels: 기능 추가

#244 🔀 :: (#243) 이메일 전송 버그
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/error/GlobalErrorCode.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/exception/SendEmailRejectedException.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/thirdparty/ses/AwsSESAdapter.java
Labels: 버그, 리팩토링

#246 🔀 :: (#245) 이메일 인증번호 발송api response값 추가
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/api/SendEmailAuthCodePort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/api/dto/response/SendEmailAuthCodeResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/usecase/SendEmailAuthCodeUseCase.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/presentation/AuthWebAdapter.java
Labels: chore

#248 🔀 :: (#247) 회사 업데이트 수정
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/usecase/UpdateCompanyNameUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/request/DomainUpdateCompanyRequest.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/UpdateCompanyUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/domain/User.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/TeacherWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/dto/request/WebUpdateCompanyRequest.java
Labels: chore

#234 🔀 :: (#222) 태그가 존재하는 학생 상세보기 오류
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/spi/MySkillPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/StudentDetailResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/StudentInformation.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherQueryMySkillPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherQueryStudentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/QueryStudentDetailUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/QueryStudentDetailTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/QueryStudentDetailUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/MySkillPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
Labels: 버그

#250 🔀 :: (#249) 로컬문서 생성 시 response 추가
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/CreateLocalDocumentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/request/DomainCreateLocalDocumentRequest.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/response/CreateLocalDocumentResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/CommandDocumentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CreateLocalDocumentUseCase.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/dto/request/WebCreateLocalDocumentRequest.java
Labels: 리팩토링, 기능 추가

#252 🔀 :: (#251) 대기문서 조회 api studentId로 조회
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryStayDocumentUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryStayDocumentUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
Labels: chore

#254 🔀 :: (#253) 각종 이메일 보내기 & 이메일 템플릿 설정
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/enums/EmailType.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/spi/SendMailPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/usecase/SendEmailAuthCodeUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/DocumentQueryUserPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/RequestLocalDocumentToPublicUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherCommandUserPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/ChangeCompanyPasswordUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/CreateCompanyUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/CreateFeedbackUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/RequestLocalDocumentToPublicUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/CreateCompanyUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/CreateFeedbackUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/ResetPasswordTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/thirdparty/ses/AwsSESAdapter.java
Labels: 리팩토링, 기능 추가

#256 🔀 :: 로컬 문서 생성 시 request 객체 빈 문자열로 치환
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/CreateLocalDocumentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/request/DomainCreateLocalDocumentRequest.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CreateLocalDocumentUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CreateLocalDocumentUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/dto/request/WebCreateLocalDocumentRequest.java
Labels: chore

#257 🔀 :: (#255) LOCAL -> STAY 문서 흐름 처리
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/error/DocumentErrorCode.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/exception/StayDocumentAlreadyExist.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/QueryDocumentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/RequestLocalDocumentToPublicUseCase.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
Labels: chore

#259 🔀 :: (#258) 베타 테스트용 학생 생성 !긴급
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/spi/RandomStringPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/api/BetaCreateUserPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/api/dto/response/BetaCreateUserResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/spi/StudentQueryUserPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/spi/StudentRandomStringPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/spi/StudentSecurityPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/usecase/BetaCreateUserUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/error/UserErrorCode.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/exception/UserAlreadyExistsException.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/entity/StudentEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/presentation/StudentWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/presentation/dto/request/BetaCreateStudentRequest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
Labels: 기능 추가

#260 🔀 :: (#255) 대기 문서 -> 공개 문서
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/DocumentCommandFeedbackPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/ApproveStayDocumentUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/spi/CommandFeedbackPort.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/ApproveStayDocumentUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/entity/DocumentEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/FeedbackPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/FeedbackRepository.java
Labels: chore

#262 🔀 :: (#261) 로컬 문서 생성 시 request 추가
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/CreateLocalDocumentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/request/DomainCreateDocumentRequest.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CreateLocalDocumentUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CreateLocalDocumentUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/dto/request/WebCreateLocalDocumentRequest.java
Labels: 리팩토링

#265 🔀 :: (#264) 프론트 요구사항 반영
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/api/dto/response/MyInfoResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/api/dto/response/MySkillElement.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/spi/StudentQueryMySkillPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/usecase/QueryMyInfoUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/student/usecase/GetMyInfoUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/MySkillPersistenceAdapter.java
Labels: chore

#267 🔀 :: (#266) TransactionAspect가 정상적으로 동작하지 않음
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/FeedbackPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/MySkillPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/aop/TransactionAspect.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/db/TransactionConfiguration.java
Labels: 버그, 리팩토링

#269 🔀 :: (#268) 학생 리스트 보기 값 변경
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/StudentElementByGradeClassNum.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
Labels: chore

#270 🔀 :: 계정 발급 API 변경
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/api/BetaCreateUserPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/usecase/BetaCreateUserUseCase.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/presentation/StudentWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/presentation/dto/request/BetaCreateStudentRequest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
Labels: chore
