Repository EntryDSM/Yapaghetti, pull requests merged in 2022-07, with the labels that each got.

#19 🔀 :: (#5) AwsS3 Adapter 추가
  yapaghetti-infrastructure/build.gradle
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/error/GlobalErrorCode.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/exception/.gitKeep
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/exception/ImageExtensionInvalidException.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/exception/ImageNotFoundException.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/infrastructure/s3/.gitKeep
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/infrastructure/s3/AwsS3Adapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/infrastructure/s3/type/ImageType.java
Labels: 프로젝트 설정

#22 🔀 :: (#20) 패키지 정리
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/api/SignInPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/api/dto/request/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/api/dto/response/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/domain/User.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/error/UserErrorCode.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/exception/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/CommandUserPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/QueryUserPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/SignInUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/user/api/SignInPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/user/spi/CommandUserPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/user/spi/QueryUserPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/user/usecase/SignInUseCase.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/CompanyPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/CompanyRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/entity/CompanyAuthority.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/entity/CompanyEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/.gitKeep
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/.gitKeep
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/company/persistence/entity/CompanyAuthority.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/student/.gitKeep
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/teacher/.gitKeep
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/principle/AuthDetailsService.java
Labels: 프로젝트 설정

#26 🔀 :: (#24) role 획일화
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/domain/UserRole.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/CompanyPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/CompanyRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/entity/CompanyAuthority.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/entity/CompanyEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/entity/UserEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/entity/UserRole.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityRole.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/principle/AuthDetails.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/principle/AuthDetailsService.java
Labels: 리팩토링

#31 🔀 :: (#30) CodeCov 세팅
  .github/workflows/CI.yml
  build.gradle
  yapaghetti-application/build.gradle
  yapaghetti-infrastructure/build.gradle
Labels: 기능 추가

#28 🔀 :: (#18) 로그인
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/api/SignInPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/api/dto/request/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/api/dto/request/DomainSignInRequest.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/api/dto/response/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/api/dto/response/SignInResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/domain/User.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/error/UserErrorCode.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/exception/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/exception/UserInvalidPasswordException.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/exception/UserInvalidRoleException.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/exception/UserNotFoundException.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/QueryUserPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/UserJwtPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/UserSecurityPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/SignInUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/SignInUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/mapper/UserMapper.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/presentation/UserWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/presentation/dto/request/.gitKeep
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/presentation/dto/request/WebSignInRequest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/exception/InternalServerErrorException.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/property/JwtProperties.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityFacadeAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/jwt/.gitKeep
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/jwt/JwtTokenProvider.java
Labels: 기능 추가

#38 🔀 :: (#37) 사용하지 않는 패키지 삭제
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/student/.gitKeep
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/teacher/.gitKeep
Labels: 프로젝트 설정

#36 🔀 :: (#21) Jwt Filter
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/UserJwtPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/SignInUseCase.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/config/FilterConfig.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/config/SecurityConfig.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/error/GlobalErrorCode.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/exception/InvalidTokenException.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/exception/InvalidTokenTypeException.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/exception/UserCredentialsNotFoundException.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/jwt/JwtTokenFilter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/jwt/JwtTokenProvider.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/principle/AuthDetails.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/principle/AuthDetailsService.java
Labels: 기능 추가

#35 🔀 :: (#33) querydsl setting
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserQuerydslExtension.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserQuerydslImpl.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/querydsl/QuerydslConfig.java
Labels: 프로젝트 설정

#39 🔀 :: (#32) 문서 & 피드백 Entity 생성
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/DocumentType.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/.gitKeep
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/entity/DocumentEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/.gitKeep
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/FeedBackPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/FeedBackRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/entity/FeedBackEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/entity/FeedBackEntityId.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/entity/UserEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/entity/BaseIDEntity.java
Labels: 프로젝트 설정

#42 🔀 :: (#40) 최초 비밀번호 수정 Api
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/api/FirstPasswordUpdatePort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/api/dto/request/DomainFirstPasswordUpdateRequest.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/domain/User.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/CommandUserPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/QueryUserPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/UserSecurityPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/FirstPasswordUpdateUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/FirstPasswordUpdateUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/mapper/UserMapper.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/entity/UserEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/presentation/UserWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/presentation/dto/request/WebFirstPasswordUpdateRequest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/config/SecurityConfig.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityFacadeAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/principle/AuthDetails.java
Labels: 기능 추가

#44 🔀 :: (#41) 태그 & 마이스킬 엔티티
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/domain/TagType.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/entity/CompanyEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/entity/DocumentEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/entity/FeedBackEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/MySkillPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/MySkillRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/entity/MySkillEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/entity/MySkillEntityId.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/TagPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/TagRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/entity/TagEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/entity/UserEntity.java
Labels: 프로젝트 설정

#46 🔀 :: (#45) 선생님 Entity
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/.gitKeep
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/persistence/TeacherPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/persistence/TeacherRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/persistence/entity/TeacherEntity.java
Labels: 프로젝트 설정

#48 🔀 :: (#27) 로컬 문서 생성 API
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/annotation/Port.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/CreateLocalDocumentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/request/DomainCreateLocalDocumentRequest.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/domain/Document.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/domain/DocumentType.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/error/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/exception/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/CommandDocumentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CreateLocalDocumentUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/domain/User.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CreateLocalDocumentTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/mapper/DocumentMapper.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/entity/DocumentEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/dto/request/WebCreateLocalDocumentRequest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/entity/UserEntity.java
Labels: 기능 추가

#50 🔀 :: (#49) 학생 entity
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/entity/CompanyEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/.gitKeep
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/StudentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/StudentRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/entity/StudentEntity.java
Labels: 프로젝트 설정

#52 🔀 :: (#51) id -> UUID로 수정 & PasswordEncoder Bean 등록 & 나머지 수정
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/domain/Document.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CreateLocalDocumentUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/domain/User.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/QueryUserPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/UserJwtPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/UserSecurityPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/FirstPasswordUpdateUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/SignInUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CreateLocalDocumentTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/FirstPasswordUpdateUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/entity/CompanyEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/mapper/DocumentMapper.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/entity/DocumentEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/entity/FeedBackEntityId.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/entity/MySkillEntityId.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/entity/StudentEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/entity/TagEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/persistence/entity/TeacherEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/mapper/UserMapper.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/entity/UserEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/presentation/dto/request/WebSignInRequest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/annotation/Adapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/annotation/config/GlobalComponentScan.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/entity/BaseUUIDEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/error/filter/GlobalErrorFilter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityFacadeAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/jwt/JwtTokenProvider.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/principle/AuthDetails.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/principle/AuthDetailsService.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/infrastructure/s3/AwsS3Adapter.java
Labels: 프로젝트 설정, 리팩토링, 기능 추가, chore

#58 🔀 :: (#57) COMPANY UserRole 삭제
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/domain/UserRole.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
Labels: 프로젝트 설정

#60 🔀 :: (#59) 공개 문서 조회 API
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/QueryPublicDocumentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/response/QueryPublicDocumentResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/error/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/error/DocumentErrorCode.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/exception/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/exception/DocumentNotFoundException.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/QueryDocumentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryPublicDocumentUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryPublicDocumentTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/mapper/DocumentMapper.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
Labels: 기능 추가

#61 🔀 :: (#55) 학생 aggregate + mapper + 자잘한 수정
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/domain/Student.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/error/TagErrorCode.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/exception/TagNotFoundException.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/CompanyRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/mapper/StudentMapper.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/entity/StudentEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/.gitKeep
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/TagPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/TagRepository.java
Labels: 프로젝트 설정, chore

#63 🔀 :: (#62) 공개 문서 로컬로 복사 API
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/CopyPublicDocumentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/QueryDocumentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CopyPublicDocumentUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CopyPublicDocumentTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
Labels: 기능 추가

#68 🔀 :: (#67) Aggregate 불변객체로 변경
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/domain/Document.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/domain/Student.java
Labels: chore

#65 🔀 :: (#8) 태그 생성 기능 개발
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/api/AddTagPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/api/dto/request/DomainAddTagRequest.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/domain/Tag.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/error/TagErrorCode.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/exception/AlreadyExistsTagException.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/spi/CommandTagPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/spi/QueryTagPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/AddTagUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/AddTagUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/mapper/TagMapper.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/TagPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/TagRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/entity/TagEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/presentation/TagWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/presentation/dto/request/WebAddTagRequest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
Labels: 기능 추가

#56 🔀 :: (#6) upload image
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/image/api/UploadImagePort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/image/api/dto/response/ImageUrlResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/image/error/ImageErrorCode.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/image/exception/ImageExtensionInvalidException.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/image/exception/ImageNotFoundException.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/image/spi/UploadS3Port.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/image/spi/type/ImageType.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/image/usecase/UploadImageUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/image/usecase/UploadImageUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/image/presentation/ImageWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/error/GlobalErrorCode.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/infrastructure/s3/AwsS3Adapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/infrastructure/s3/type/ImageType.java
Labels: 기능 추가

#77 🔀 :: (#7) 태그 검색
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/api/GetTagListPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/api/dto/response/TagElement.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/api/dto/response/TagListResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/spi/QueryTagPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/GetTagListUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/GetTagListUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/TagPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/TagRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/presentation/TagWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
Labels: 기능 추가

#91 🔀 :: (#90) 기술 태그 설정 miss
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/spi/CommandMySkillPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/AddMySkillUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/AddMySkillUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/.gitKeep
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/MySkillPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/MySkillRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/entity/MySkillEntityId.java
Labels: 기능 추가

#89 🔀 :: (#81) 유저 정보 수정 Api
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/api/UpdateUserInformationPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/api/dto/request/DomainUpdateUserInformationRequest.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/domain/User.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/UpdateUserInformationUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/UpdateUserInformationUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/presentation/UserWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/presentation/dto/request/WebUpdateUserInformationRequest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
Labels: 기능 추가

#98 🔀 :: (#97) 버그 해결
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/mapper/CompanyMapper.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/CompanyPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/CompanyRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/entity/CompanyEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/mapper/DocumentMapper.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/entity/DocumentEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/entity/FeedBackEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/MySkillPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/MySkillRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/entity/MySkillEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/mapper/StudentMapper.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/entity/StudentEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/presentation/TagWebAdapter.java
Labels: 버그

#94 🔀 :: (#54) 내 정보 조회 api
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/spi/QueryMySkillPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/api/GetMyInfoPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/api/dto/response/MyInfoResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/spi/QueryStudentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/spi/StudentSecurityPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/usecase/GetMyInfoUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/spi/QueryTagPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/SetMajorTagUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/student/usecase/GetMyInfoUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/SetMajorTagUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/mapper/MySkillMapper.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/MySkillPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/MySkillRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/presentation/StudentWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/TagPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityFacadeAdapter.java
Labels: 기능 추가

#102 🔀 :: (#101) 피드백 반영 완료 api
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/.gitKeep
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/domain/Feedback.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/error/FeedbackErrorCode.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/exception/FeedbackNotFoundException.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/spi/CommandFeedbackPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/spi/QueryFeedbackPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/api/ReflectFeedbackPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/usecase/ReflectFeedbackUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/student/usecase/ReflectFeedbackUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/mapper/FeedbackMapper.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/FeedBackPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/FeedbackPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/FeedbackRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/entity/FeedBackEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/entity/FeedBackEntityId.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/presentation/StudentWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
Labels: 기능 추가

#100 🔀 :: (#72) 공개 요청 문서 취소 API
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/CancelStayDocumentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/domain/Document.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/CommandDocumentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/DocumentSecurityPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CancelStayDocumentUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/UpdateLocalDocumentUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CancelStayDocumentUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/entity/DocumentEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/annotation/config/GlobalComponentScan.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityFacadeAdapter.java
Labels: 기능 추가, chore

#115 🔀 :: (#115) 기업 문서 확인 시작일과 마감일 추가
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/domain/Company.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/mapper/CompanyMapper.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/entity/CompanyEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserRepository.java
Labels: 리팩토링

#109 🔀 :: (#108) exists와 관련된 Exception Adapter로 이동하기
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/spi/QueryTagPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/AddTagUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/DeleteTagUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/SetMajorTagUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/AddTagUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/DeleteTagUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/tag/usecase/SetMajorTagUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/TagPersistenceAdapter.java
Labels: 리팩토링

#99 🔀 :: (#95) 전체 학생 리스트 조회 Api
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/api/QueryStudentListPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/api/dto/request/DomainQueryStudentListRequest.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/api/dto/response/QueryStudentListResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/api/dto/response/StudentElement.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/spi/CompanyQueryStudentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/usecase/QueryStudentListUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/spi/StudentPort.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/company/usecase/QueryStudentListUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/entity/CompanyEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/presentation/CompanyWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/entity/FeedBackEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/my_skill/persistence/entity/MySkillEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/entity/StudentEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/persistence/entity/TeacherEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
Labels: 기능 추가

#96 🔀 :: (#85) 대기 문서 조회 API
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/QueryStayDocumentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/response/FeedbackElement.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/response/QueryStayDocumentResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/DocumentQueryFeedbackPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/QueryDocumentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CopyPublicDocumentUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CreateLocalDocumentUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/DeleteLocalDocumentUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryLocalDocumentUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryStayDocumentUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/UpdateLocalDocumentUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/spi/FeedbackPort.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CancelStayDocumentUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryStayDocumentTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/UpdateLocalDocumentTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/mapper/FeedbackMapper.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/FeedbackPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/FeedbackRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/entity/FeedbackEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/feedback/persistence/entity/FeedbackEntityId.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
Labels: 기능 추가

#121 🔀 :: (#119) 로컬 문서 리스트 조회 API
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/QueryLocalDocumentListPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/response/DocumentElement.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/response/QueryLocalDocumentListResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/DocumentQueryTagPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/QueryDocumentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryLocalDocumentListUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryLocalDocumentListUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/entity/StudentEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
Labels: 기능 추가, chore

#125 🔀 :: (#124) 공개 문서 조회 비즈니스 로직 수정
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/QueryDocumentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryPublicDocumentUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryPublicDocumentTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
Labels: 버그

#140 🔀 :: (#29) 토큰 리프레시
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/api/TokenRefreshPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/api/dto/response/TokenRefreshResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/domain/RefreshToken.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/error/UserErrorCode.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/exception/RefreshTokenNotFoundException.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/CommandRefreshTokenPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/QueryRefreshTokenPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/RefreshTokenPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/UserJwtPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/dto/SpiTokenResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/SignInUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/TokenRefreshUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/SignInUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/user/usecase/TokenRefreshUseCaseTest.java
  yapaghetti-infrastructure/build.gradle
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/mapper/RefreshTokenMapper.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/RefreshTokenPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/RefreshTokenRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/entity/RefreshTokenEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/presentation/UserWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/jwt/JwtTokenProvider.java
Labels: 기능 추가

#130 🔀 :: (#127) 공개 / 대기 문서 미리보기 API
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/QueryStayAndPublicDocumentPreviewPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/response/QueryStayAndPublicDocumentPreviewResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/api/dto/response/StayAndPublicDocumentElement.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/DocumentQueryStudentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/QueryDocumentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryStayAndPublicDocumentPreviewUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/spi/StudentPort.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryStayAndPublicDocumentPreviewUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/DocumentRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
Labels: 기능 추가, chore

#137 🔀 :: (#120) 기업 정보 상세 보기
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/spi/QueryCompanyPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/usecase/UpdateCompanyNameUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/GetCompanyDetailPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/CompanyDetailResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherQueryCompanyPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherQueryUserPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/DeleteCompanyUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/GetCompanyDetailUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/UserPort.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/company/usecase/UpdateCompanyNameUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/DeleteCompanyTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/GetCompanyDetailTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/CompanyPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/TeacherWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
Labels: 기능 추가

#145 🔀 :: (#144) 이메일 인증번호 확인 api
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/api/VerifyEmailAuthCodePort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/domain/AuthCode.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/domain/AuthCodeType.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/error/AuthCodeErrorCode.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/exception/AuthCodeAlreadyTimeOutException.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/exception/AuthCodeAlreadyVerifiedException.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/exception/InvalidAuthCodeException.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/usecase/SendEmailAuthCodeUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/usecase/VerifyEmailAuthCodeUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/auth/usecase/SendEmailAuthCodeUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/auth/usecase/VerifyEmailAuthCodeUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/mapper/AuthCodeMapper.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/persistence/AuthCodeRepository.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/persistence/entity/AuthCodeEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/presentation/AuthWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/util/GenerateRandomStringUtilsAdapter.java
Labels: 기능 추가

#139 🔀 :: (#117) 회사 검색
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/QueryCompanyListPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/CompanyElement.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/CompanyListResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherQueryCompanyPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/QueryCompanyListUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/QueryCompanyListTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/CompanyPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/TeacherWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
Labels: 기능 추가

#141 🔀 :: (#118) 학생 상세 정보
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/QueryStudentDetailPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/StudentDetailResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherQueryStudentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/QueryStudentDetailUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/QueryStudentDetailTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/TeacherWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
Labels: 기능 추가

#146 🔀 :: (#138) 로컬 문서 리스트 조회 Api 버그 수정 & 기타 에러 수정
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/spi/DocumentQueryTagPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryLocalDocumentListUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/spi/TagPort.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryLocalDocumentListUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/presentation/DocumentWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/tag/persistence/TagPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/mapper/RefreshTokenMapper.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/jwt/JwtTokenProvider.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/infrastructure/ses/AwsSESConfig.java
Labels: 버그, chore

#158 🔀 :: (#156) TeacherWebAdapter 수정
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/TeacherWebAdapter.java
Labels: 버그

#162 🔀 :: (#161) CD 설정
  .github/workflows/CD.yml
Labels: 프로젝트 설정

#148 🔀 :: (#147) 기업 비번 초기화
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/spi/RandomStringPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/domain/Company.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/ChangeCompanyPasswordPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/ChangeCompanyPasswordResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherRandomStringPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherSecurityPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/ChangeCompanyPasswordUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/domain/User.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/UserPort.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/ResetPasswordTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/TeacherWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/util/GenerateRandomStringUtilsAdapter.java
Labels: 기능 추가

#160 🔀 :: (#159) 학생 정보 변경
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/error/AuthCodeErrorCode.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/exception/AuthCodeNotVerifiedException.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/auth/spi/AuthCodePort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/api/UpdateMyInfoPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/domain/UpdateType.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/spi/StudentCommandUserPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/spi/StudentQueryAuthCodePort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/usecase/UpdateMyInfoUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/domain/User.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/UserPort.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/student/usecase/UpdateMyInfoUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/presentation/StudentWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/TeacherWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
Labels: 기능 추가

#149 🔀 :: (#134) 학생 리스트 조회
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/TeacherQueryStudentListPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/StudentElementByGradeClassNum.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/StudentListResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherQueryStudentPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/TeacherQueryStudentListUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/TeacherQueryStudentListTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/document/persistence/entity/DocumentEntity.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/student/persistence/StudentPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/TeacherWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
Labels: 기능 추가

#151 🔀 :: (#110) 기업 생성
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/spi/CommandCompanyPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/usecase/UpdateCompanyNameUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/CreateCompanyPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/request/DomainNewCompanyRequest.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/api/dto/response/NewCompanyResponse.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherCommandCompanyPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/spi/TeacherCommandUserPort.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/CreateCompanyUseCase.java
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/UpdateCompanyUseCase.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/ApproveStayDocumentUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CopyPublicDocumentUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/CreateLocalDocumentUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/DeletePublicDocumentUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryProtectedDocumentUrlUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryPublicDocumentUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/QueryStayDocumentUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/RejectStayDocumentUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/UpdateLocalDocumentUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/document/usecase/UpdateStayDocumentUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/CreateCompanyUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/CreateFeedbackUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/DeleteCompanyUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/DeleteStudentUseCaseTest.java
  yapaghetti-application/src/test/java/kr/hs/entrydsm/yapaghetti/domain/teacher/usecase/GetCompanyDetailUseCaseTest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/company/persistence/CompanyPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/TeacherWebAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/teacher/presentation/dto/request/WebCreateCompanyRequest.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/persistence/UserPersistenceAdapter.java
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/security/SecurityConfig.java
Labels: 기능 추가

#168 🔀 :: (#53) Security Base64 Encode Error
  yapaghetti-infrastructure/src/main/java/kr/hs/entrydsm/yapaghetti/global/property/JwtProperties.java
Labels: 버그

#172 🔀 :: (#171) StudentCommandUserPort를 UserPort에 extends
  yapaghetti-application/src/main/java/kr/hs/entrydsm/yapaghetti/domain/user/spi/UserPort.java
Labels: 버그
